#!/usr/bin/env python2

import sys
import subprocess
import os

files = sys.argv

src_files = files[1:-1]

dst_files = files[-1]

pwdraw = subprocess.check_output('pwd',shell=True)
pwd = pwdraw[0:-1]

for i in src_files:
	if os.path.isdir(i):
		print "\nERROR: '"+i+"' is a directory , cannot copy a directory "
		exit()
	else:
		if os.path.exists(i) and '/' in i:
			fsrc = open(i,'r')
			src_data = fsrc.read()
			if '/' in dst_files:
				fdst = open(dst_files,'a')
				fdst.write(src_data)
			else:
				fdst = open(pwd+'/'+dst_files,'a')
				fdst.write(src_data)

		elif os.path.exists(pwd+'/'+i):
			fsrc = open(pwd+'/'+i,'r')
			src_data = fsrc.read()
			if '/' in dst_files:
				fdst = open(dst_files,'a')
				fdst.write(src_data)
			else:
				fdst = open(pwd+'/'+dst_files,'a')
				fdst.write(src_data)


		else:
			print "\npycp: cannot stat '"+i+"': No such file or directory"
			exit()

