#!/usr/bin/env python2

import sys
import subprocess
import os

files = sys.argv

src_files = files[1:-1]

dst_files = files[-1]

pwd = subprocess.check_output('pwd',shell=True)

for i in src_files:
	if os.path.exists(i) and / in i:
		fsrc = open(i,'r')
		src_data = fsrc.read()
		if / in dst_file:
			fdst = open(dst_files,'a')
			fdst.write(src_data)
		else:
			fdst = open(pwd+'/'+dst_files,'a')
			fdst.write(src_data)

	elif os.path.exists(pwd+'/'+i):
		fsrc = open(pwd+'/'+i,'r')
		src_data = fsrc.read()
		if / in dst_file:
			fdst = open(dst_files,'a')
			fdst.write(src_data)
		else:
			fdst = open(pwd+'/'+dst_files,'a')
			fdst.write(src_data)


	else:
		print "pycp: cannot stat '"+i+"': No such file or directory"
		exit()


